import React, { createContext, useContext, useState, useEffect } from "react";

export type LanguageType = "en" | "fr" | "ar";

type LanguageContextValue = {
  language: LanguageType;
  setLanguage: (lang: LanguageType) => void;
  t: (key: keyof typeof translations.en) => string;
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguageState] = useState<LanguageType>(() => {
    const saved = localStorage.getItem("evogym_language") as LanguageType;
    return saved === "fr" || saved === "ar" || saved === "en" ? saved : "en";
  });

  const setLanguage = (lang: LanguageType) => {
    setLanguageState(lang);
    localStorage.setItem("evogym_language", lang);
  };

  useEffect(() => {
    const isRtl = language === "ar";
    document.documentElement.dir = isRtl ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: keyof typeof translations.en): string => {
    const dict = translations[language] || translations.en;
    const value = dict[key] ?? translations.en[key];
    return typeof value === "string" ? value : String(key);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

export const translations = {
  en: {
    // Nav links
    nav_home: "Home",
    nav_benefits: "Benefits",
    nav_classes: "Our Classes",
    nav_contact: "Contact Us",
    nav_signin: "Sign In",
    nav_become_member: "Become a member",
    nav_subscription: "Subscription",
    nav_logout: "Logout",
    nav_admin: "Admin",
    nav_profile: "Profile",

    // Home
    home_desc: "Built for heavy training, explosive conditioning, and disciplined performance. Step into elite coaching, iron-ready studios, and a program designed to push your limits.",
    home_join_now: "Join Now",
    home_learn_more: "Learn More",

    // Benefits
    benefits_title_1: "OUR FEATURES",
    benefits_title_2: "BUILT FOR PEOPLE CHASING ",
    benefits_title_span: "STRENGTH & RESULTS",
    benefits_desc_1: "Built for people who train with purpose. Heavy equipment, ruthless conditioning, expert coaching, and classes that turn effort into measurable strength.",
    benefits_desc_2: "Train inside an industrial performance space built for serious lifting, high-output circuits, and no-excuse consistency. Every session is structured to sharpen strength, stamina, and control.",
    benefits_desc_3: "From barbell work to conditioning blocks, the goal is simple: move heavier, recover faster, and leave stronger than you came in.",
    benefits_item_1_title: "State of the Art Facilities",
    benefits_item_1_desc: "Equipped with competition-grade barbells, heavy-duty racks, turf paths, and custom conditioning rigs.",
    benefits_item_2_title: "100's of Diverse Classes",
    benefits_item_2_desc: "From high-intensity conditioning circuits to core work, mobility, and strength-focused coaching routines.",
    benefits_item_3_title: "Expert and Certified Trainers",
    benefits_item_3_desc: "Professional coaches focused on mechanics, safety, progression, and driving you past your plateau.",

    // Our Classes
    classes_title: "OUR CLASSES",
    classes_desc: "Pick your lane: strength, conditioning, combat-inspired circuits, mobility, and performance training built for people who want results they can measure.",

    // Contact Us
    contact_join: "JOIN NOW",
    contact_shape: " TO GET IN SHAPE",
    contact_desc: "Claim your first performance session. Tell us your goal, your current level, and how hard you are ready to train.",
    contact_placeholder_name: "NAME",
    contact_placeholder_email: "EMAIL",
    contact_placeholder_message: "MESSAGE",
    contact_err_required: "This field is required.",
    contact_err_email: "Invalid email address.",
    contact_err_max_char: "Max length is 100 characters.",
    contact_err_max_msg: "Max length is 2000 characters.",
    contact_submit: "SUBMIT",
    contact_toast: "Message sent! We'll get back to you shortly.",

    // Authentication (Login/Register)
    auth_welcome_admin: "Welcome back, Admin",
    auth_welcome_member: "Become a member",
    auth_create_desc: "Create a local prototype account and step into the member area.",
    auth_login_desc: "Sign in to access your dashboard, plans, and coaches.",
    auth_name: "Name",
    auth_email: "Email",
    auth_password: "Password",
    auth_create_btn: "Create Account",
    auth_signin_btn: "Sign In",
    auth_already: "Already have access? ",
    auth_no_account: "New to Evogym? ",
    auth_sign_in_link: "Sign in",
    auth_create_link: "Become a member",
    auth_error_existing: "An account with this email address already exists.",
    auth_error_required: "Name, email, and password are required.",
    auth_error_login: "Invalid email or password.",
    auth_quick_member: "Sign In as Member",
    auth_quick_admin: "Sign In as Admin",
    auth_quick_desc_member: "Demo account with active plan & settings",
    auth_quick_desc_admin: "Demo account with portal controls & inbox",

    // Member Profile & Dashboard
    profile_welcome: "Welcome back, ",
    profile_title: "Member Dashboard",
    profile_email: "Email Address",
    profile_tier: "Membership Tier",
    profile_status_none: "No Active Plan",
    profile_status_plan: " Plan",
    profile_time_left: "Time Left on Plan",
    profile_no_timer: "No active subscription",
    profile_expired: "Subscription Expired",
    profile_settings_title: "Profile Settings",
    profile_phone: "Phone Number",
    profile_goals: "Personal Goals",
    profile_phone_empty: "Not added yet",
    profile_goals_empty: "No goals added yet",
    profile_goals_placeholder: "Build strength, lose fat, improve conditioning...",
    profile_save_btn: "Save Changes",
    profile_updated_toast: "Profile updated.",
    profile_avatar_label: "Change Avatar",
    profile_avatar_none: "Upload Image",
    profile_tab_dash: "Dashboard & Subscription",
    profile_tab_settings: "Profile Settings",
    profile_tab_coaches: "Coaches",
    profile_tab_equipment: "Equipment",
    profile_display_name: "Display Name",
    profile_time_remaining: "Time Remaining",
    profile_edit_heading: "Edit Your Member Profile",
    profile_upload_avatar: "Upload Avatar",
    profile_save_profile: "Save Profile",
    profile_explore_classes: "Explore Gym Classes",
    profile_contact_support: "Contact Support",
    profile_coaches_heading: "Our Expert Coaches",
    profile_equipment_heading: "Gym Equipment & Facilities",
    profile_equip_name: "Name",
    profile_equip_category: "Category",
    profile_equip_qty: "Quantity Available",
    profile_equip_status: "Status",

    // Plan Selection
    plans_title: "CHOOSE YOUR TIER",
    plans_desc: "Select the subscription level that matches your training schedule. No hidden fees.",
    plans_select: "Select Plan",
    plans_current: "Current Plan",
    plans_expires: "Expires on: ",
    plans_profile: "Profile",
    plans_logout: "Logout",
    plans_subtitle: "Subscription Plans",
    plans_heading: "Choose Your Access",
    plans_proto: "Prototype payment flow: selecting a plan updates your member profile with a 30-day subscription.",
    plans_current_plan: "Current Plan",
    plans_available: "Available Plan",
    plans_active: "Active Plan",

    // Admin Dashboard
    admin_portal: "Admin Portal",
    admin_logout: "Logout",
    admin_tab_members: "Manage Members",
    admin_tab_coaches: "Manage Coaches",
    admin_tab_subscriptions: "Manage Subscriptions",
    admin_tab_equipment: "Manage Equipment",
    admin_tab_inbox: "Inbox",
    admin_tab_classes: "Manage Classes",
    admin_members_heading: "Registered Gym Members",
    admin_col_name: "Name",
    admin_col_email: "Email",
    admin_col_tier: "Tier",
    admin_col_expires: "Subscription Expires",
    admin_col_actions: "Actions",
    admin_no_plan: "No active plan",
    admin_expired: " (Expired)",
    admin_delete: "Delete",
    admin_save: "Save Changes",
    admin_cancel: "Cancel",
    admin_edit: "Edit",
    admin_add_plan: "Add Subscription Plan",
    admin_edit_plan: "Edit Plan: ",
    admin_plan_name: "Plan Name",
    admin_plan_price: "Monthly Price",
    admin_description: "Description",
    admin_features: "Features (one per line)",
    admin_add_btn: "Add Plan",
    admin_update_btn: "Update Plan",
    admin_existing_plans: "Existing Plans",
    admin_coaches_heading: "Coaches",
    admin_add_coach: "Add Coach",
    admin_edit_coach: "Edit Coach: ",
    admin_coach_name: "Coach Name",
    admin_coach_spec: "Specialization",
    admin_coach_bio: "Bio",
    admin_add_coach_btn: "Add Coach",
    admin_update_coach_btn: "Update Coach",
    admin_equipment_heading: "Equipment",
    admin_add_equipment: "Add Equipment",
    admin_edit_equipment: "Edit Equipment: ",
    admin_eq_name: "Equipment Name",
    admin_eq_type: "Type",
    admin_eq_qty: "Quantity",
    admin_eq_status: "Status",
    admin_add_eq_btn: "Add Equipment",
    admin_update_eq_btn: "Update Equipment",
    admin_inbox_heading: "Member Inbox",
    admin_col_from: "From",
    admin_col_message: "Message",
    admin_col_read: "Read",
    admin_mark_read: "Mark Read",
    admin_classes_heading: "Gym Classes",
    admin_add_class: "Add Class",
    admin_edit_class: "Edit Class: ",
    admin_class_name: "Class Name",
    admin_class_desc: "Description",
    admin_class_img: "Image URL",
    admin_add_class_btn: "Add Class",
    admin_update_class_btn: "Update Class",
    admin_add_days: "+7 Days",
    admin_remove_days: "-7 Days",
    admin_plan_placeholder: "Plan 1",
    admin_feature_placeholder: "One feature per line",
    admin_coach_name_placeholder: "e.g. Marcus Vance",
    admin_coach_spec_placeholder: "e.g. HIIT & Endurance",
    admin_coach_bio_placeholder: "Write a brief background...",
    admin_equipment_placeholder: "e.g. Rowers",
    admin_class_name_placeholder: "e.g. Cardio Classes",
    admin_class_desc_placeholder: "Short description shown on the card overlay...",
    admin_type_strength: "Strength",
    admin_type_cardio: "Cardio",
    admin_type_accessories: "Accessories",
    admin_type_other: "Other",
    admin_status_operational: "Operational",
    admin_status_maintenance: "Under Maintenance",
    admin_inbox_empty: "Messages submitted via the Contact form will appear here.",
    admin_no_image: "No image selected",
    admin_upload_image: "Upload Image",
    admin_change_image: "Change Image",
    plans_monthly: "/month",
    plan_1_name: "Plan 1",
    plan_1_desc: "Entry access for members starting their training routine.",
    plan_1_features: ["Gym floor access", "Locker room access", "Basic equipment use"],
    plan_2_name: "Plan 2",
    plan_2_desc: "Performance access for consistent strength and conditioning work.",
    plan_2_features: ["Everything in Plan 1", "Group classes", "Monthly progress check"],
    plan_3_name: "Plan 3",
    plan_3_desc: "Full access for members who want coaching and priority support.",
    plan_3_features: ["Everything in Plan 2", "Priority class access", "Coach consultation"],
    auth_quick_coach: "Sign In as Coach",
    auth_quick_desc_coach: "Demo coach with assigned classes & schedule",
    coach_portal: "Coach Portal",
    coach_dashboard: "Coach Dashboard",
    coach_tab_overview: "Overview",
    coach_tab_profile: "Professional Profile",
    coach_tab_classes: "My Classes",
    coach_tab_schedule: "Schedule",
    coach_welcome: "Welcome back",
    coach_assigned_classes: "Assigned Classes",
    coach_weekly_slots: "Weekly Slots",
    coach_profile_heading: "Edit Professional Profile",
    coach_specialization: "Specialization",
    coach_bio: "Professional Bio",
    coach_phone: "Phone Number",
    coach_avatar: "Upload Avatar",
    coach_profile_saved: "Professional profile updated.",
    coach_no_classes: "No classes are assigned to you yet.",
    coach_edit_class: "Edit Class",
    coach_class_saved: "Class updated.",
    schedule_heading: "Weekly Schedule",
    schedule_class: "Class",
    schedule_day: "Weekday",
    schedule_start: "Start Time",
    schedule_duration: "Duration (minutes)",
    schedule_capacity: "Capacity",
    schedule_add: "Add Slot",
    schedule_save: "Save Slot",
    schedule_empty: "No weekly slots yet.",
    schedule_conflict: "That class already has a slot at this day and time.",
    schedule_minutes: "min",
    schedule_spots: "spots",
    weekday_monday: "Monday",
    weekday_tuesday: "Tuesday",
    weekday_wednesday: "Wednesday",
    weekday_thursday: "Thursday",
    weekday_friday: "Friday",
    weekday_saturday: "Saturday",
    weekday_sunday: "Sunday",
    admin_coach_email: "Account Email",
    admin_coach_password: "Initial / New Password",
    admin_coach_password_hint: "Leave blank to keep the current password",
    admin_coach_account_active: "Account Active",
    admin_coach_account_inactive: "No Account",
    admin_coach_duplicate: "That email is already in use.",
    admin_coach_invalid: "Name, specialization, email, and password are required.",
    admin_assign_coach: "Assigned Coach",
    admin_unassigned: "Unassigned",
    classes_coach: "Coach",
    classes_schedule: "Weekly Times",

    // Footer
    footer_desc: "Strength-focused coaching, heavy training rooms, and high-performance classes for members who want to work.",
    footer_rights: "EVOGYM All Rights Reserved.",
    footer_links: "Links",
    footer_classes: "Strength Classes",
    footer_coaching: "Performance Coaching",
    footer_membership: "Membership",
    footer_contact: "Contact Us",
    footer_contact_desc: "Ready to train harder? Talk to our team.",
    footer_phone: "(213)552-409-383",
  },
  fr: {
    // Nav links
    nav_home: "Accueil",
    nav_benefits: "Avantages",
    nav_classes: "Nos Classes",
    nav_contact: "Contactez-nous",
    nav_signin: "Connexion",
    nav_become_member: "Devenir membre",
    nav_subscription: "Abonnement",
    nav_logout: "Déconnexion",
    nav_admin: "Admin",
    nav_profile: "Profil",

    // Home
    home_desc: "Conçu pour un entraînement intensif, un conditionnement explosif et des performances disciplinées. Profitez d'un coaching d'élite, de studios prêts à l'emploi et d'un programme conçu pour repousser vos limites.",
    home_join_now: "Rejoindre",
    home_learn_more: "En savoir plus",

    // Benefits
    benefits_title_1: "NOS ATOUTS",
    benefits_title_2: "CONÇU POUR CEUX QUI VEULENT DE LA ",
    benefits_title_span: "FORCE & DES RÉSULTATS",
    benefits_desc_1: "Construit pour les personnes qui s'entraînent avec un but précis. Équipement lourd, conditionnement sans merci, coaching d'experts et cours qui transforment l'effort en force mesurable.",
    benefits_desc_2: "Entraînez-vous dans un espace de performance industriel conçu pour le levage lourd, les circuits intenses et la régularité sans excuse. Chaque séance est structurée pour renforcer la force, l'endurance et le contrôle.",
    benefits_desc_3: "Du travail à la barre aux séances de conditionnement, l'objectif est simple : soulever plus lourd, récupérer plus vite et repartir plus fort qu'à votre arrivée.",
    benefits_item_1_title: "Installations de Pointe",
    benefits_item_1_desc: "Équipé de barres de niveau compétition, de racks ultra-robustes, de pistes synthétiques et de structures de conditionnement sur mesure.",
    benefits_item_2_title: "Des Centaines de Cours Variés",
    benefits_item_2_desc: "Des circuits de conditionnement haute intensité au travail de gainage, de mobilité et des programmes axés sur la force.",
    benefits_item_3_title: "Entraîneurs Certifiés et Experts",
    benefits_item_3_desc: "Coachs professionnels focalisés sur la mécanique, la sécurité, la progression et le dépassement de vos limites.",

    // Our Classes
    classes_title: "NOS CLASSES",
    classes_desc: "Choisissez votre voie : force, conditionnement physique, circuits inspirés du combat, mobilité et entraînement de performance conçus pour ceux qui veulent des résultats mesurables.",

    // Contact Us
    contact_join: "REJOIGNEZ-NOUS",
    contact_shape: " POUR RETROUVER LA FORME",
    contact_desc: "Réservez votre première séance d'évaluation. Dites-nous vos objectifs, votre niveau actuel et l'intensité que vous êtes prêt à y consacrer.",
    contact_placeholder_name: "NOM",
    contact_placeholder_email: "EMAIL",
    contact_placeholder_message: "MESSAGE",
    contact_err_required: "Ce champ est obligatoire.",
    contact_err_email: "Adresse email invalide.",
    contact_err_max_char: "La longueur maximale est de 100 caractères.",
    contact_err_max_msg: "La longueur maximale est de 2000 caractères.",
    contact_submit: "ENVOYER",
    contact_toast: "Message envoyé ! Nous vous répondrons dans les plus brefs délais.",

    // Authentication (Login/Register)
    auth_welcome_admin: "Content de vous revoir, Admin",
    auth_welcome_member: "Devenir membre",
    auth_create_desc: "Créez un compte prototype local et accédez à l'espace membre.",
    auth_login_desc: "Connectez-vous pour accéder à votre tableau de bord, plans et entraîneurs.",
    auth_name: "Nom",
    auth_email: "Adresse email",
    auth_password: "Mot de passe",
    auth_create_btn: "Créer un compte",
    auth_signin_btn: "Se connecter",
    auth_already: "Vous avez déjà un compte ? ",
    auth_no_account: "Nouveau chez Evogym ? ",
    auth_sign_in_link: "Se connecter",
    auth_create_link: "Devenir membre",
    auth_error_existing: "Un compte avec cette adresse email existe déjà.",
    auth_error_required: "Le nom, l'email et le mot de passe sont requis.",
    auth_error_login: "Email ou mot de passe incorrect.",
    auth_quick_member: "Connexion Membre",
    auth_quick_admin: "Connexion Admin",
    auth_quick_desc_member: "Compte démo avec plan actif & réglages",
    auth_quick_desc_admin: "Compte démo avec accès portail & messages",

    // Member Profile & Dashboard
    profile_welcome: "Content de vous revoir, ",
    profile_title: "Tableau de Bord Membre",
    profile_email: "Adresse email",
    profile_tier: "Type d'abonnement",
    profile_status_none: "Aucun abonnement actif",
    profile_status_plan: " Plan",
    profile_time_left: "Temps restant sur le plan",
    profile_no_timer: "Aucun abonnement actif",
    profile_expired: "Abonnement Expiré",
    profile_settings_title: "Paramètres du Profil",
    profile_phone: "Numéro de téléphone",
    profile_goals: "Objectifs personnels",
    profile_phone_empty: "Non renseigné",
    profile_goals_empty: "Aucun objectif ajouté",
    profile_goals_placeholder: "Développer ma force, perdre du gras, améliorer mon endurance...",
    profile_save_btn: "Sauvegarder",
    profile_updated_toast: "Profil mis à jour.",
    profile_avatar_label: "Changer l'avatar",
    profile_avatar_none: "Télécharger une image",
    profile_tab_dash: "Tableau de Bord & Abonnement",
    profile_tab_settings: "Paramètres de Profil",
    profile_tab_coaches: "Entraîneurs",
    profile_tab_equipment: "Équipement",
    profile_display_name: "Nom d'affichage",
    profile_time_remaining: "Temps restant",
    profile_edit_heading: "Modifier votre profil membre",
    profile_upload_avatar: "Télécharger un avatar",
    profile_save_profile: "Sauvegarder le profil",
    profile_explore_classes: "Explorer les cours",
    profile_contact_support: "Contacter le support",
    profile_coaches_heading: "Nos entraîneurs experts",
    profile_equipment_heading: "Équipements & Installations",
    profile_equip_name: "Nom",
    profile_equip_category: "Catégorie",
    profile_equip_qty: "Quantité disponible",
    profile_equip_status: "Statut",

    // Plan Selection
    plans_title: "CHOISISSEZ VOTRE FORMULE",
    plans_desc: "Sélectionnez le niveau d'abonnement correspondant à votre rythme d'entraînement. Sans frais cachés.",
    plans_select: "Sélectionner ce plan",
    plans_current: "Abonnement Actuel",
    plans_expires: "Expire le : ",
    plans_profile: "Profil",
    plans_logout: "Déconnexion",
    plans_subtitle: "Plans d'abonnement",
    plans_heading: "Choisissez Votre Accès",
    plans_proto: "Flux de paiement prototype : sélectionner un plan met à jour votre profil membre avec un abonnement de 30 jours.",
    plans_current_plan: "Plan Actuel",
    plans_available: "Plan Disponible",
    plans_active: "Plan Actif",

    // Admin Dashboard
    admin_portal: "Portail Admin",
    admin_logout: "Déconnexion",
    admin_tab_members: "Membres",
    admin_tab_coaches: "Entraîneurs",
    admin_tab_subscriptions: "Abonnements",
    admin_tab_equipment: "Équipements",
    admin_tab_inbox: "Boîte de réception",
    admin_tab_classes: "Cours",
    admin_members_heading: "Membres inscrits",
    admin_col_name: "Nom",
    admin_col_email: "Email",
    admin_col_tier: "Formule",
    admin_col_expires: "Expiration abonnement",
    admin_col_actions: "Actions",
    admin_no_plan: "Aucun plan actif",
    admin_expired: " (Expiré)",
    admin_delete: "Supprimer",
    admin_save: "Sauvegarder",
    admin_cancel: "Annuler",
    admin_edit: "Modifier",
    admin_add_plan: "Ajouter un plan",
    admin_edit_plan: "Modifier le plan : ",
    admin_plan_name: "Nom du plan",
    admin_plan_price: "Prix mensuel",
    admin_description: "Description",
    admin_features: "Fonctionnalités (une par ligne)",
    admin_add_btn: "Ajouter le plan",
    admin_update_btn: "Mettre à jour le plan",
    admin_existing_plans: "Plans existants",
    admin_coaches_heading: "Entraîneurs",
    admin_add_coach: "Ajouter un entraîneurs",
    admin_edit_coach: "Modifier l'entraîneurs : ",
    admin_coach_name: "Nom de l'entraîneurs",
    admin_coach_spec: "Spécialisation",
    admin_coach_bio: "Biographie",
    admin_add_coach_btn: "Ajouter l'entraîneurs",
    admin_update_coach_btn: "Mettre à jour l'entraîneurs",
    admin_equipment_heading: "Équipements",
    admin_add_equipment: "Ajouter un équipement",
    admin_edit_equipment: "Modifier l'équipement : ",
    admin_eq_name: "Nom de l'équipement",
    admin_eq_type: "Type",
    admin_eq_qty: "Quantité",
    admin_eq_status: "Statut",
    admin_add_eq_btn: "Ajouter l'équipement",
    admin_update_eq_btn: "Mettre à jour l'équipement",
    admin_inbox_heading: "Boîte de réception membre",
    admin_col_from: "De",
    admin_col_message: "Message",
    admin_col_read: "Lu",
    admin_mark_read: "Marquer comme lu",
    admin_classes_heading: "Cours de gym",
    admin_add_class: "Ajouter un cours",
    admin_edit_class: "Modifier le cours : ",
    admin_class_name: "Nom du cours",
    admin_class_desc: "Description",
    admin_class_img: "URL de l'image",
    admin_add_class_btn: "Ajouter le cours",
    admin_update_class_btn: "Mettre à jour le cours",

    // Footer
    footer_desc: "Coaching axé sur la force, salles d'entraînement intensif et cours haute performance pour les membres qui veulent travailler.",
    footer_rights: "EVOGYM Tous droits réservés.",
    footer_links: "Liens",
    footer_classes: "Cours de force",
    footer_coaching: "Coaching performance",
    footer_membership: "Abonnement",
    footer_contact: "Contactez-nous",
    footer_contact_desc: "Prêt à vous entraîner plus dur ? Parlez à notre équipe.",
    footer_phone: "(213)552-409-383",
    admin_add_days: "+7 jours",
    admin_remove_days: "-7 jours",
    admin_plan_placeholder: "Plan 1",
    admin_feature_placeholder: "Une fonctionnalité par ligne",
    admin_coach_name_placeholder: "ex. Marcus Vance",
    admin_coach_spec_placeholder: "ex. HIIT et endurance",
    admin_coach_bio_placeholder: "Rédigez une brève présentation...",
    admin_equipment_placeholder: "ex. Rameurs",
    admin_class_name_placeholder: "ex. Cours cardio",
    admin_class_desc_placeholder: "Courte description affichée sur la carte...",
    admin_type_strength: "Force",
    admin_type_cardio: "Cardio",
    admin_type_accessories: "Accessoires",
    admin_type_other: "Autre",
    admin_status_operational: "Opérationnel",
    admin_status_maintenance: "En maintenance",
    admin_inbox_empty: "Les messages envoyés via le formulaire de contact apparaissent ici.",
    admin_no_image: "Aucune image sélectionnée",
    admin_upload_image: "Télécharger une image",
    admin_change_image: "Changer l'image",
    plans_monthly: "/mois",
    plan_1_name: "Plan 1",
    plan_1_desc: "Accès d'entrée pour les membres qui commencent leur entraînement.",
    plan_1_features: ["Accès à la salle", "Accès aux vestiaires", "Utilisation de l'équipement de base"],
    plan_2_name: "Plan 2",
    plan_2_desc: "Accès performance pour un travail régulier de force et de conditionnement.",
    plan_2_features: ["Tout le contenu du plan 1", "Cours collectifs", "Suivi mensuel des progrès"],
    plan_3_name: "Plan 3",
    plan_3_desc: "Accès complet pour les membres qui veulent un coaching et un support prioritaire.",
    plan_3_features: ["Tout le contenu du plan 2", "Accès prioritaire aux cours", "Consultation avec un coach"],
    auth_quick_coach: "Connexion Coach",
    auth_quick_desc_coach: "Coach démo avec cours et horaires assignés",
    coach_portal: "Portail Coach",
    coach_dashboard: "Tableau de Bord Coach",
    coach_tab_overview: "Aperçu",
    coach_tab_profile: "Profil Professionnel",
    coach_tab_classes: "Mes Cours",
    coach_tab_schedule: "Planning",
    coach_welcome: "Bon retour",
    coach_assigned_classes: "Cours Assignés",
    coach_weekly_slots: "Créneaux Hebdomadaires",
    coach_profile_heading: "Modifier le Profil Professionnel",
    coach_specialization: "Spécialisation",
    coach_bio: "Biographie Professionnelle",
    coach_phone: "Numéro de Téléphone",
    coach_avatar: "Télécharger un Avatar",
    coach_profile_saved: "Profil professionnel mis à jour.",
    coach_no_classes: "Aucun cours ne vous est encore assigné.",
    coach_edit_class: "Modifier le Cours",
    coach_class_saved: "Cours mis à jour.",
    schedule_heading: "Planning Hebdomadaire",
    schedule_class: "Cours",
    schedule_day: "Jour",
    schedule_start: "Heure de Début",
    schedule_duration: "Durée (minutes)",
    schedule_capacity: "Capacité",
    schedule_add: "Ajouter un Créneau",
    schedule_save: "Enregistrer le Créneau",
    schedule_empty: "Aucun créneau hebdomadaire.",
    schedule_conflict: "Ce cours a déjà un créneau à ce jour et cette heure.",
    schedule_minutes: "min",
    schedule_spots: "places",
    weekday_monday: "Lundi",
    weekday_tuesday: "Mardi",
    weekday_wednesday: "Mercredi",
    weekday_thursday: "Jeudi",
    weekday_friday: "Vendredi",
    weekday_saturday: "Samedi",
    weekday_sunday: "Dimanche",
    admin_coach_email: "Email du Compte",
    admin_coach_password: "Mot de Passe Initial / Nouveau",
    admin_coach_password_hint: "Laisser vide pour conserver le mot de passe actuel",
    admin_coach_account_active: "Compte Actif",
    admin_coach_account_inactive: "Aucun Compte",
    admin_coach_duplicate: "Cet email est déjà utilisé.",
    admin_coach_invalid: "Le nom, la spécialisation, l'email et le mot de passe sont requis.",
    admin_assign_coach: "Coach Assigné",
    admin_unassigned: "Non Assigné",
    classes_coach: "Coach",
    classes_schedule: "Horaires Hebdomadaires",
  },
  ar: {
    // Nav links
    nav_home: "الرئيسية",
    nav_benefits: "المميزات",
    nav_classes: "حصصنا",
    nav_contact: "اتصل بنا",
    nav_signin: "تسجيل الدخول",
    nav_become_member: "انضم كعضو",
    nav_subscription: "الاشتراكات",
    nav_logout: "تسجيل الخروج",
    nav_admin: "لوحة التحكم",
    nav_profile: "الملف الشخصي",

    // Home
    home_desc: "مُصمّم للتدريبات الثقيلة، والتمارين المكثفة، والأداء المنضبط. انطلق مع تدريب نخبة، ومرافق مجهّزة، وبرنامج يدفعك لتتجاوز حدودك.",
    home_join_now: "انضم الآن",
    home_learn_more: "اعرف المزيد",

    // Benefits
    benefits_title_1: "مميزاتنا",
    benefits_title_2: "مُصمّم لمن يسعى إلى ",
    benefits_title_span: "القوة والنتائج",
    benefits_desc_1: "مُصمّم للأشخاص الذين يتدربون بهدف. معدات ثقيلة، تمارين مكثفة، تدريب خبير، وحصص تحوّل الجهد إلى قوة قابلة للقياس.",
    benefits_desc_2: "تدرب داخل مساحة أداء صناعية مصمّمة للرفع الثقيل، وتمارين الإعداد البدني عالية الكثافة، والثبات بلا أعذار. كل جلسة مُنظّمة لشحذ القوة والتحمل والتحكم.",
    benefits_desc_3: "من تمارين الباربل إلى تمارين الإعداد البدني، الهدف بسيط: ارفع أثقل، تعافَ أسرع، وغادر أقوى مما جئت.",
    benefits_item_1_title: "مرافق حديثة",
    benefits_item_1_desc: "مجهزة بأثقال بمستوى المنافسات، رفوف ثقيلة، مسارات عشبية، وأجهزة تمارين مخصصة.",
    benefits_item_2_title: "مئات الحصص المتنوعة",
    benefits_item_2_desc: "من تمارين الإعداد البدني عالية الكثافة إلى تمارين الكور، والمرونة، وتمارين القوة بإشراف مدربين.",
    benefits_item_3_title: "مدربون خبراء ومعتمدون",
    benefits_item_3_desc: "مدربون محترفون يركزون على الميكانيكا، السلامة، التقدم، ودفعك لتجاوز حدودك.",

    // Our Classes
    classes_title: "حصصنا",
    classes_desc: "اختر مسارك: القوة، والإعداد البدني، وتمارين مستوحاة من الفنون القتالية، والمرونة، وتدريب الأداء المُصمّم للأشخاص الذين يريدون نتائج قابلة للقياس.",

    // Contact Us
    contact_join: "انضم الآن",
    contact_shape: " لتصل إلى أفضل لياقة",
    contact_desc: "احجز أول جلسة أداء لك. أخبرنا بهدفك، مستواك الحالي، ومدى استعدادك للتدريب.",
    contact_placeholder_name: "الاسم",
    contact_placeholder_email: "البريد الإلكتروني",
    contact_placeholder_message: "الرسالة",
    contact_err_required: "هذا الحقل مطلوب.",
    contact_err_email: "البريد الإلكتروني غير صالح.",
    contact_err_max_char: "الحد الأقصى 100 حرف.",
    contact_err_max_msg: "الحد الأقصى 2000 حرف.",
    contact_submit: "إرسال",
    contact_toast: "تم إرسال الرسالة! سنعود إليك قريباً.",

    // Authentication (Login/Register)
    auth_welcome_admin: "مرحباً بعودتك، مشرف",
    auth_welcome_member: "انضم كعضو",
    auth_create_desc: "أنشئ حساباً تجريبياً محلياً وادخل إلى مساحة الأعضاء.",
    auth_login_desc: "سجل الدخول للوصول إلى لوحة التحكم، الخطط، والمدربين.",
    auth_name: "الاسم",
    auth_email: "البريد الإلكتروني",
    auth_password: "كلمة المرور",
    auth_create_btn: "إنشاء حساب",
    auth_signin_btn: "تسجيل الدخول",
    auth_already: "لديك حساب بالفعل؟ ",
    auth_no_account: "جديد في Evogym؟ ",
    auth_sign_in_link: "تسجيل الدخول",
    auth_create_link: "انضم كعضو",
    auth_error_existing: "يوجد حساب بهذا البريد الإلكتروني بالفعل.",
    auth_error_required: "الاسم، البريد الإلكتروني، وكلمة المرور مطلوبة.",
    auth_error_login: "بريد إلكتروني أو كلمة مرور غير صحيحة.",
    auth_quick_member: "تسجيل الدخول كعضو",
    auth_quick_admin: "تسجيل الدخول كمشرف",
    auth_quick_desc_member: "حساب تجريبي بخطة نشطة وإعدادات",
    auth_quick_desc_admin: "حساب تجريبي مع تحكم في البوابة والرسائل",

    // Member Profile & Dashboard
    profile_welcome: "مرحباً بعودتك، ",
    profile_title: "لوحة تحكم العضو",
    profile_email: "البريد الإلكتروني",
    profile_tier: "نوع العضوية",
    profile_status_none: "لا توجد خطة نشطة",
    profile_status_plan: "الخطة",
    profile_time_left: "الوقت المتبقي على الخطة",
    profile_no_timer: "لا يوجد اشتراك نشط",
    profile_expired: "انتهى الاشتراك",
    profile_settings_title: "إعدادات الملف الشخصي",
    profile_phone: "رقم الهاتف",
    profile_goals: "الأهداف الشخصية",
    profile_phone_empty: "لم يُضف بعد",
    profile_goals_empty: "لم تُضف أهداف بعد",
    profile_goals_placeholder: "بناء القوة، خفض الدهون، وتحسين اللياقة البدنية...",
    profile_save_btn: "حفظ التغييرات",
    profile_updated_toast: "تم تحديث الملف الشخصي.",
    profile_avatar_label: "تغيير الصورة الرمزية",
    profile_avatar_none: "رفع صورة",
    profile_tab_dash: "لوحة التحكم والاشتراك",
    profile_tab_settings: "إعدادات الملف الشخصي",
    profile_tab_coaches: "المدربون",
    profile_tab_equipment: "المعدات",
    profile_display_name: "الاسم المعروض",
    profile_time_remaining: "الوقت المتبقي",
    profile_edit_heading: "تعديل ملفك الشخصي",
    profile_upload_avatar: "رفع صورة رمزية",
    profile_save_profile: "حفظ الملف الشخصي",
    profile_explore_classes: "استكشف حصص النادي",
    profile_contact_support: "اتصل بالدعم",
    profile_coaches_heading: "مدربونا الخبراء",
    profile_equipment_heading: "معدات ومرافق الجيم",
    profile_equip_name: "الاسم",
    profile_equip_category: "الفئة",
    profile_equip_qty: "الكمية المتاحة",
    profile_equip_status: "الحالة",

    // Plan Selection
    plans_title: "اختر باقتك",
    plans_desc: "اختر مستوى الاشتراك الذي يناسب جدول تدريبك. لا رسوم خفية.",
    plans_select: "اختر الخطة",
    plans_current: "الخطة الحالية",
    plans_expires: "تنتهي في: ",
    plans_profile: "الملف الشخصي",
    plans_logout: "تسجيل الخروج",
    plans_subtitle: "خطط الاشتراك",
    plans_heading: "اختر باقتك المناسبة",
    plans_proto: "نموذج دفع تجريبي: اختيار باقة يحدّث ملف عضويتك باشتراك لمدة 30 يوماً.",
    plans_current_plan: "الخطة الحالية",
    plans_available: "الخطة المتاحة",
    plans_active: "الخطة النشطة",

    // Admin Dashboard
    admin_portal: "بوابة المشرف",
    admin_logout: "تسجيل الخروج",
    admin_tab_members: "إدارة الأعضاء",
    admin_tab_coaches: "إدارة المدربين",
    admin_tab_subscriptions: "إدارة الاشتراكات",
    admin_tab_equipment: "إدارة المعدات",
    admin_tab_inbox: "صندوق الوارد",
    admin_tab_classes: "إدارة الحصص",
    admin_members_heading: "الأعضاء المسجلون",
    admin_col_name: "الاسم",
    admin_col_email: "البريد الإلكتروني",
    admin_col_tier: "الباقة",
    admin_col_expires: "انتهاء الاشتراك",
    admin_col_actions: "الإجراءات",
    admin_no_plan: "لا توجد خطة نشطة",
    admin_expired: " (منتهي)",
    admin_delete: "حذف",
    admin_save: "حفظ التغييرات",
    admin_cancel: "إلغاء",
    admin_edit: "تعديل",
    admin_add_plan: "إضافة خطة اشتراك",
    admin_edit_plan: "تعديل الخطة: ",
    admin_plan_name: "اسم الخطة",
    admin_plan_price: "السعر الشهري",
    admin_description: "الوصف",
    admin_features: "الميزات (ميزة واحدة في كل سطر)",
    admin_add_btn: "إضافة خطة",
    admin_update_btn: "تحديث الخطة",
    admin_existing_plans: "الخطط الحالية",
    admin_coaches_heading: "المدربون",
    admin_add_coach: "إضافة مدرب",
    admin_edit_coach: "تعديل المدرب: ",
    admin_coach_name: "اسم المدرب",
    admin_coach_spec: "التخصص",
    admin_coach_bio: "السيرة الذاتية",
    admin_add_coach_btn: "إضافة مدرب",
    admin_update_coach_btn: "تحديث المدرب",
    admin_equipment_heading: "المعدات",
    admin_add_equipment: "إضافة معدات",
    admin_edit_equipment: "تعديل المعدة: ",
    admin_eq_name: "اسم المعدة",
    admin_eq_type: "النوع",
    admin_eq_qty: "الكمية",
    admin_eq_status: "الحالة",
    admin_add_eq_btn: "إضافة معدات",
    admin_update_eq_btn: "تحديث المعدات",
    admin_inbox_heading: "صندوق وارد الأعضاء",
    admin_col_from: "من",
    admin_col_message: "الرسالة",
    admin_col_read: "مقروء",
    admin_mark_read: "تحديد كمقروء",
    admin_classes_heading: "حصص النادي",
    admin_add_class: "إضافة حصة",
    admin_edit_class: "تعديل الحصة: ",
    admin_class_name: "اسم الحصة",
    admin_class_desc: "الوصف",
    admin_class_img: "رابط الصورة",
    admin_add_class_btn: "إضافة حصة",
    admin_update_class_btn: "تحديث الحصة",

    // Footer
    footer_desc: "تدريب يركّز على القوة، وصالات للتدريب الثقيل، وحصص عالية الأداء للأعضاء الذين يريدون بذل جهد حقيقي.",
    footer_rights: "جميع الحقوق محفوظة لدى EVOGYM.",
    footer_links: "روابط",
    footer_classes: "فصول القوة",
    footer_coaching: "تدريب الأداء",
    footer_membership: "العضوية",
    footer_contact: "اتصل بنا",
    footer_contact_desc: "مستعد للتدرب بقوة؟ تحدث مع فريقنا.",
    footer_phone: "(213)552-409-383",
    admin_add_days: "+7 أيام",
    admin_remove_days: "-7 أيام",
    admin_plan_placeholder: "الخطة 1",
    admin_feature_placeholder: "ميزة واحدة في كل سطر",
    admin_coach_name_placeholder: "مثال: ماركوس فانس",
    admin_coach_spec_placeholder: "مثال: تدريب متقطع عالي الكثافة وتحمل",
    admin_coach_bio_placeholder: "اكتب نبذة مختصرة...",
    admin_equipment_placeholder: "مثال: أجهزة التجديف",
    admin_class_name_placeholder: "مثال: حصص الكارديو",
    admin_class_desc_placeholder: "وصف مختصر يظهر على بطاقة الحصة...",
    admin_type_strength: "قوة",
    admin_type_cardio: "كارديو",
    admin_type_accessories: "ملحقات",
    admin_type_other: "أخرى",
    admin_status_operational: "قيد التشغيل",
    admin_status_maintenance: "تحت الصيانة",
    admin_inbox_empty: "ستظهر هنا الرسائل المرسلة عبر نموذج التواصل.",
    admin_no_image: "لم يتم اختيار صورة",
    admin_upload_image: "رفع صورة",
    admin_change_image: "تغيير الصورة",
    plans_monthly: "/شهرياً",
    plan_1_name: "الخطة 1",
    plan_1_desc: "دخول أساسي للأعضاء الذين يبدأون روتينهم التدريبي.",
    plan_1_features: ["دخول إلى أرضية النادي", "دخول إلى غرف تبديل الملابس", "استخدام المعدات الأساسية"],
    plan_2_name: "الخطة 2",
    plan_2_desc: "دخول للأداء لمن يلتزم بتدريبات القوة والإعداد البدني.",
    plan_2_features: ["كل ما في الخطة 1", "حصص جماعية", "متابعة شهرية للتقدم"],
    plan_3_name: "الخطة 3",
    plan_3_desc: "دخول كامل للأعضاء الذين يريدون تدريباً شخصياً ودعماً ذا أولوية.",
    plan_3_features: ["كل ما في الخطة 2", "أولوية حجز الحصص", "استشارة مع مدرب"],
    auth_quick_coach: "تسجيل الدخول كمدرب",
    auth_quick_desc_coach: "حساب مدرب تجريبي مع حصص وجدول",
    coach_portal: "بوابة المدرب",
    coach_dashboard: "لوحة تحكم المدرب",
    coach_tab_overview: "نظرة عامة",
    coach_tab_profile: "الملف المهني",
    coach_tab_classes: "حصصي",
    coach_tab_schedule: "الجدول",
    coach_welcome: "مرحباً بعودتك",
    coach_assigned_classes: "الحصص المسندة",
    coach_weekly_slots: "المواعيد الأسبوعية",
    coach_profile_heading: "تعديل الملف المهني",
    coach_specialization: "التخصص",
    coach_bio: "النبذة المهنية",
    coach_phone: "رقم الهاتف",
    coach_avatar: "رفع صورة",
    coach_profile_saved: "تم تحديث الملف المهني.",
    coach_no_classes: "لم تُسند إليك أي حصص بعد.",
    coach_edit_class: "تعديل الحصة",
    coach_class_saved: "تم تحديث الحصة.",
    schedule_heading: "الجدول الأسبوعي",
    schedule_class: "الحصة",
    schedule_day: "اليوم",
    schedule_start: "وقت البداية",
    schedule_duration: "المدة (بالدقائق)",
    schedule_capacity: "السعة",
    schedule_add: "إضافة موعد",
    schedule_save: "حفظ الموعد",
    schedule_empty: "لا توجد مواعيد أسبوعية بعد.",
    schedule_conflict: "توجد للحصة جلسة في اليوم والوقت نفسيهما.",
    schedule_minutes: "دقيقة",
    schedule_spots: "مكاناً",
    weekday_monday: "الاثنين",
    weekday_tuesday: "الثلاثاء",
    weekday_wednesday: "الأربعاء",
    weekday_thursday: "الخميس",
    weekday_friday: "الجمعة",
    weekday_saturday: "السبت",
    weekday_sunday: "الأحد",
    admin_coach_email: "البريد الإلكتروني للحساب",
    admin_coach_password: "كلمة المرور الأولية / الجديدة",
    admin_coach_password_hint: "اتركها فارغة للاحتفاظ بكلمة المرور الحالية",
    admin_coach_account_active: "الحساب نشط",
    admin_coach_account_inactive: "لا يوجد حساب",
    admin_coach_duplicate: "هذا البريد الإلكتروني مستخدم بالفعل.",
    admin_coach_invalid: "الاسم والتخصص والبريد الإلكتروني وكلمة المرور مطلوبة.",
    admin_assign_coach: "المدرب المسند",
    admin_unassigned: "غير مسند",
    classes_coach: "المدرب",
    classes_schedule: "المواعيد الأسبوعية",
  }
};

export const formatPlanName = (planName: string, language: LanguageType) => {
  if (language !== "ar") return planName;

  const defaultPlanNumber = /^Plan\s+(\d+)$/i.exec(planName)?.[1];
  return defaultPlanNumber ? `الخطة ${defaultPlanNumber}` : planName;
};

export const getLocalizedPlanContent = <T extends {
  id: string;
  name: string;
  description: string;
  features: string[];
}>(plan: T, language: LanguageType): T => {
  if (language !== "ar") return plan;

  const localizedPlans = {
    "plan-1": {
      name: translations.ar.plan_1_name,
      description: translations.ar.plan_1_desc,
      features: translations.ar.plan_1_features,
    },
    "plan-2": {
      name: translations.ar.plan_2_name,
      description: translations.ar.plan_2_desc,
      features: translations.ar.plan_2_features,
    },
    "plan-3": {
      name: translations.ar.plan_3_name,
      description: translations.ar.plan_3_desc,
      features: translations.ar.plan_3_features,
    },
  };

  const localizedPlan = localizedPlans[plan.id as keyof typeof localizedPlans];
  return localizedPlan ? { ...plan, ...localizedPlan } : plan;
};
